INSERT INTO DRONE_MODEL(MODEL, WEIGHT_LIMIT_GR)
VALUES ('LIGHTWEIGHT', 100);

INSERT INTO DRONE_MODEL(MODEL, WEIGHT_LIMIT_GR)
VALUES ('MIDDLEWEIGHT', 200);

INSERT INTO DRONE_MODEL(MODEL, WEIGHT_LIMIT_GR)
VALUES ('CRUISERWEIGHT', 300);

INSERT INTO DRONE_MODEL(MODEL, WEIGHT_LIMIT_GR)
VALUES ('HEAVYWEIGHT', 500);

COMMIT;