INSERT INTO DRONES(SERIAL_NUMBER, MODEL, BATTERY_LEVEL, STATE)
VALUES ('serial-number_1', 'LIGHTWEIGHT',  85, 'LOADED');

INSERT INTO DRONES(SERIAL_NUMBER, MODEL, BATTERY_LEVEL, STATE)
VALUES ('serial-number_2', 'LIGHTWEIGHT',  75, 'IDLE');

INSERT INTO DRONES(SERIAL_NUMBER, MODEL, BATTERY_LEVEL, STATE)
VALUES ('serial-number_3', 'MIDDLEWEIGHT',  15, 'IDLE');

INSERT INTO DRONES(SERIAL_NUMBER, MODEL, BATTERY_LEVEL, STATE)
VALUES ('serial-number_4', 'MIDDLEWEIGHT',  100, 'DELIVERING');

INSERT INTO DRONES(SERIAL_NUMBER, MODEL, BATTERY_LEVEL, STATE)
VALUES ('serial-number_5', 'CRUISERWEIGHT',  60, 'IDLE');

INSERT INTO DRONES(SERIAL_NUMBER, MODEL, BATTERY_LEVEL, STATE)
VALUES ('serial-number_6', 'CRUISERWEIGHT',  30, 'DELIVERED');

INSERT INTO DRONES(SERIAL_NUMBER, MODEL, BATTERY_LEVEL, STATE)
VALUES ('serial-number_7', 'CRUISERWEIGHT',  80, 'IDLE');

INSERT INTO DRONES(SERIAL_NUMBER, MODEL, BATTERY_LEVEL, STATE)
VALUES ('serial-number_8', 'HEAVYWEIGHT',  50, 'LOADED');

INSERT INTO DRONES(SERIAL_NUMBER, MODEL, BATTERY_LEVEL, STATE)
VALUES ('serial-number_9', 'HEAVYWEIGHT',  40, 'RETURNING');

INSERT INTO DRONES(SERIAL_NUMBER, MODEL, BATTERY_LEVEL, STATE)
VALUES ('serial-number_10', 'HEAVYWEIGHT',  24, 'IDLE');

COMMIT;