INSERT INTO DRONE_MEDICATION(DRONE_SERIAL_NUMBER, MEDICATION_CODE, count)
VALUES ('serial-number_1', 'med_code_2', 1);
INSERT INTO DRONE_MEDICATION(DRONE_SERIAL_NUMBER, MEDICATION_CODE, count)
VALUES ('serial-number_1', 'med_code_4', 1);

INSERT INTO DRONE_MEDICATION(DRONE_SERIAL_NUMBER, MEDICATION_CODE, count)
VALUES ('serial-number_8', 'med_code_3', 2);
INSERT INTO DRONE_MEDICATION(DRONE_SERIAL_NUMBER, MEDICATION_CODE, count)
VALUES ('serial-number_8', 'med_code_2', 1);
INSERT INTO DRONE_MEDICATION(DRONE_SERIAL_NUMBER, MEDICATION_CODE, count)
VALUES ('serial-number_8', 'med_code_1', 3);

COMMIT;